include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_declarations: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_required_param: warning
    dead_code: info
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
